# Generated by Django 5.2.7 on 2025-11-02 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('passwordHash', models.CharField(blank=True, max_length=255)),
                ('phoneNumber', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CameraDetectedPerson',
            fields=[
                ('cameraDetectedPersonId', models.AutoField(primary_key=True, serialize=False)),
                ('embedding', models.JSONField(default=list)),
                ('potentiallyLost', models.BooleanField(default=False)),
                ('isElderly', models.BooleanField(default=False)),
                ('isDisabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LastSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Camira XXX', max_length=255)),
                ('time', models.DateTimeField(auto_now=True)),
                ('coordinates', models.JSONField(default=list)),
                ('CDPid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CDPid', to='base.cameradetectedperson')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityStaff',
            fields=[
                ('staffId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('passwordHash', models.CharField(blank=True, max_length=255)),
                ('phoneNumber', models.CharField(blank=True, max_length=20)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to='base.admin')),
            ],
        ),
        migrations.CreateModel(
            name='SearchData',
            fields=[
                ('searchID', models.AutoField(primary_key=True, serialize=False)),
                ('requestTime', models.DateTimeField(auto_now_add=True)),
                ('isProcessing', models.BooleanField(default=True)),
                ('isFound', models.BooleanField(default=False)),
                ('requestedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestedBy', to='base.securitystaff')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('familyMemberId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('idNumber', models.CharField(blank=True, max_length=25)),
                ('phoneNumber', models.CharField(blank=True, max_length=20)),
                ('relation', models.CharField(blank=True, max_length=50)),
                ('servicedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicedBy', to='base.securitystaff')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAccepted', models.BooleanField(default=False)),
                ('cameraDetectedPersonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cameradetectedperson')),
                ('searchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.searchdata')),
            ],
            options={
                'unique_together': {('searchID', 'cameraDetectedPersonId', 'isAccepted')},
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('cameradetectedperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='base.cameradetectedperson')),
                ('personId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('isMale', models.BooleanField(default=True)),
                ('idNumber', models.CharField(blank=True, max_length=25, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, unique=True)),
                ('knownLocation', models.CharField(blank=True, default='Unknown', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='person_videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='person_images/')),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('isLost', models.BooleanField(default=True)),
                ('relatTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatTo', to='base.familymember')),
            ],
            options={
                'unique_together': {('firstName', 'lastName', 'isMale')},
            },
            bases=('base.cameradetectedperson',),
        ),
    ]
