# Generated by Django 5.2.7 on 2025-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='person',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='person_images/'),
        ),
        migrations.AddField(
            model_name='person',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='person_images/'),
        ),
        migrations.AddField(
            model_name='person',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='person_images/'),
        ),
        migrations.AddField(
            model_name='person',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='person_images/'),
        ),
        migrations.AlterField(
            model_name='lastseen',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
