# Generated by Django 5.2.7 on 2025-11-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_image_person_image_1_person_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='idNumber',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
