# Generated by Django 5.2.7 on 2025-11-11 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_person_idnumber_alter_person_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='servicedBy',
        ),
        migrations.AddField(
            model_name='person',
            name='reportedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicedBy', to='base.securitystaff'),
        ),
    ]
