# Generated by Django 5.2.7 on 2025-11-11 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_familymember_servicedby_person_reportedby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='knownLocation',
            new_name='LastLocation',
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='person',
            name='reportedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicedBy', to='base.securitystaff'),
        ),
    ]
