# Generated by Django 5.2.7 on 2025-11-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_knownlocation_person_lastlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameradetectedperson',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
    ]
