# Generated by Django 5.2.7 on 2025-11-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_cameradetectedperson_ai_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastseen',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
